//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:7.0.10
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooxApp.Module.ShipmentList.DTO
{
    
    
    public class order_ocean_v1DTO
    {
        
        private string _order_no;
        
        private string _carrier_name;
        
        private int _total_qty;
        
        private System.DateTime _shipping_date;
        
        private string _shipper_name;
        
        private string _consignee_name;
        
        private string _workflow_status;
        
        public virtual string order_no
        {
            get
            {
                return this._order_no;
            }
            set
            {
                this._order_no = value;
            }
        }
        
        public virtual string carrier_name
        {
            get
            {
                return this._carrier_name;
            }
            set
            {
                this._carrier_name = value;
            }
        }
        
        public virtual int total_qty
        {
            get
            {
                return this._total_qty;
            }
            set
            {
                this._total_qty = value;
            }
        }
        
        public virtual System.DateTime shipping_date
        {
            get
            {
                return this._shipping_date;
            }
            set
            {
                this._shipping_date = value;
            }
        }
        
        public virtual string shipper_name
        {
            get
            {
                return this._shipper_name;
            }
            set
            {
                this._shipper_name = value;
            }
        }
        
        public virtual string consignee_name
        {
            get
            {
                return this._consignee_name;
            }
            set
            {
                this._consignee_name = value;
            }
        }
        
        public virtual string workflow_status
        {
            get
            {
                return this._workflow_status;
            }
            set
            {
                this._workflow_status = value;
            }
        }
    }
}
